---
title: "Bootstrapping"
output: github_document
date: "2025-11-13"
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)
```

Simulate two datasets.

```{r}
set.seed(1) #for reproducibility

n_samp = 250

sim_df_const =
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst =
  sim_df_const |> 
  mutate(
    error = 0.75 * error * x, #NON constant error! Violates regression assumption
    y = 2 + 3 * x + error)

```

Look at the data

```{r}
sim_df_const |> 
  ggplot(aes(x = x, y = y)) +
  geom_point()

sim_df_nonconst |> 
  ggplot(aes(x = x, y = y)) +
  geom_point()
```

What does `lm` do for these?

```{r}
sim_df_const |> 
  lm(y ~ x, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)

sim_df_nonconst |> 
  lm(y ~ x, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

Write a function to draw a bootstrap sample.

```{r}
boot_sample = function(df){
  
  sample_frac(df, size = 1, replace = TRUE)
  
}
```

Does this work?


```{r}
sim_df_nonconst |> 
  boot_sample() |> 
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "lm", se = FALSE) +
  xlim(c(-2, 4)) +
  ylim(c(-5, 16))
```

So I want to formalize this a bit and extract results.

```{r}
boot_straps =
  tibble(
    iter = 1:10
  ) |> 
  mutate(
    bootstrap_sample = map(iter, \(i) boot_sample(df = sim_df_nonconst))
  )
```

(quick check)

```{r}
boot_straps |> 
  pull(bootstrap_sample) |> 
  nth(1) |> 
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "lm", se = FALSE) +
  xlim(c(-2, 4)) +
  ylim(c(-5, 16))
```



